### ISSUE TITLE
[Bug] [5.3.0] Does not install with Win10: "Failed to Load Native Binding"

### ISSUE THREAD

**Issue by joshuactk** [hockyy/miteiru#63]
**Describe the bug**
Miteiru does not install with Windows 10.

**To Reproduce**
1. Install the 5.3.0 exe from the Release section
2. Run into the bug

**Expected behavior**
I was expecting the installation to complete.

**Screenshots**
![Screenshot_20240926_170659](https://github.com/user-attachments/assets/645aea5c-d506-439d-98ec-28807e4ce8bf)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.19044.3324

**Additional context**
Are there software prerequisites I should take care of beforehand?

**Comment by hockyy** [comment]
no

**Comment by hockyy** [comment]
Might be an issue when upgrading the version of Electron

**Comment by joshuactk** [comment]
![Screenshot_20241004_001404](https://github.com/user-attachments/assets/8b20ab1e-9648-4bda-8c8f-0aaefc9d8886)
v5.5.0 works with Win10!
